curl -o macbu-2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/macbu-2.htm
curl -o macbu-1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/macbu-1.htm
curl -o 426mac-2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/426mac-2.htm
curl -o 426mac-1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/426mac-1.htm
curl -o macvc-2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/macvc-2.htm
curl -o macvc-1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/macvc-1.htm
curl -o 4-22-sb2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/4-22-sb2.htm
curl -o 4-22-sb1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/4-22-sb1.htm
curl -o maccon-2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/maccon-2.htm
curl -o maccon-1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/maccon-1.htm
curl -o macsto-2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/macsto-2.htm
curl -o macsto-1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/macsto-1.htm
curl -o maccsb-2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/maccsb-2.htm
curl -o maccsb-1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/maccsb-1.htm
curl -o nwcmac2a.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/nwcmac2a.htm
curl -o nwcmac1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/nwcmac1.htm
curl -o 040806g2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/040806g2.htm
curl -o 040806g1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/040806g1.htm
curl -o gacmac-2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/gacmac-2.htm
curl -o gacmac-1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/gacmac-1.htm
curl -o macham-2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/macham-2.htm
curl -o macham-1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/macham-1.htm
curl -o car-mac2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/car-mac2.htm
curl -o car-mac1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/car-mac1.htm
curl -o 032906-2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/032906-2.htm
curl -o 032906-1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/032906-1.htm
curl -o 0317-car.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/0317-car.htm
curl -o 0317-mla.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/0317-mla.htm
curl -o rf-mac.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/rf-mac.htm
curl -o 0316-psu.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/0316-psu.htm
curl -o 0315-mes.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/0315-mes.htm
curl -o 0315-wpu.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/0315-wpu.htm
curl -o 0313-hc.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/0313-hc.htm
curl -o 0313-uws.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/0313-uws.htm
curl -o 0312-den.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/0312-den.htm
curl -o 0312-snc.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/0312-snc.htm
