curl -o 0312-osu.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats11/0312-osu.htm
curl -o 0312-sj.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats11/0312-sj.htm
curl -o 0313-nec.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats11/0313-nec.htm
curl -o 0313-umm.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats11/0313-umm.htm
curl -o 0314-fu.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats11/0314-fu.htm
curl -o 0314osu.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats11/0314osu.htm
curl -o 0316-fsc.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats11/0316-fsc.htm
curl -o 0316-kc.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats11/0316-kc.htm
curl -o 0316-law.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats11/0316-law.htm
curl -o 0317-rip.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats11/0317-rip.htm
curl -o 0318-bc.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats11/0318-bc.htm
curl -o 0319-chi.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats11/0319-chi.htm
curl -o 0319-trn.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats11/0319-trn.htm
curl -o 0320-car.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats11/0320-car.htm
curl -o 0405mac1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats11/0405mac1.htm
curl -o 0405mac2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats11/0405mac2.htm
curl -o 0407-sm1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats11/0407-sm1.htm
curl -o 0407-sm2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats11/0407-sm2.htm
curl -o 0409-so1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats11/0409-so1.htm
curl -o 0409-so2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats11/0409-so2.htm
curl -o 0410-bl1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats11/0410-bl1.htm
curl -o 0410-bl2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats11/0410-bl2.htm
curl -o 041301sb.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats11/041301sb.htm
curl -o 041302sb.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats11/041302sb.htm
curl -o 0415-ac1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats11/0415-ac1.htm
curl -o 0415-ac2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats11/0415-ac2.htm
curl -o 0421-sc1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats11/0421-sc1.htm
curl -o 0421-sc2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats11/0421-sc2.htm
curl -o 0423-cc1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats11/0423-cc1.htm
curl -o 0423-cc2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats11/0423-cc2.htm
curl -o 0426-hu1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats11/0426-hu1.htm
curl -o 0426-hu2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats11/0426-hu2.htm
curl -o 0428-ga1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats11/0428-ga1.htm
curl -o 0428-ga2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats11/0428-ga2.htm
curl -o 4-30-sb1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats11/4-30-sb1.htm
curl -o 4-30-sb2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats11/4-30-sb2.htm
curl -o csbmac1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats11/csbmac1.htm
curl -o csbmac2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats11/csbmac2.htm
