curl -o gac-35.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats01/gac-35.htm
curl -o gac-34.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats01/gac-34.htm
curl -o beth-33.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats01/beth-33.htm
curl -o beth-32.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats01/beth-32.htm
curl -o olaf-31.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats01/olaf-31.htm
curl -o olaf-30.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats01/olaf-30.htm
curl -o csb-29.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats01/csb-29.htm
curl -o csb-28.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats01/csb-28.htm
curl -o augs-27.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats01/augs-27.htm
curl -o augs-26x.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats01/augs-26x.htm
curl -o ham-25.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats01/ham-25.htm
curl -o ham-24.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats01/ham-24.htm
curl -o cord23.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats01/cord23.htm
curl -o conc-22.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats01/conc-22.htm
curl -o csc-21.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats01/csc-21.htm
curl -o csc-20.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats01/csc-20.htm
curl -o ust19.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats01/ust19.htm
curl -o ust-18.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats01/ust-18.htm
curl -o carl17.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats01/carl17.htm
curl -o carl16.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats01/carl16.htm
curl -o 472mac.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats01/472mac.htm
curl -o 47mac.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats01/47mac.htm
curl -o umm-01.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats01/umm-01.htm
curl -o nw-02.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats01/nw-02.htm
curl -o nw-01.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats01/nw-01.htm
