curl -o con-36.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats02/con-36.htm
curl -o con-35.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats02/con-35.htm
curl -o csc-34.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats02/csc-34.htm
curl -o csc-33.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats02/csc-33.htm
curl -o csb-2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats02/csb-2.htm
curl -o csb-1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats02/csb-1.htm
curl -o 51mac2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats02/51mac2.htm
curl -o 51mac.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats02/51mac.htm
curl -o ust-28.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats02/ust-28.htm
curl -o ust-27.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats02/ust-27.htm
curl -o carmach1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats02/carmach1.htm
curl -o olaf-20.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats02/olaf-20.htm
curl -o olaf-19.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats02/olaf-19.htm
curl -o mac2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats02/mac2.htm
curl -o mac1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats02/mac1.htm
curl -o macham2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats02/macham2.htm
curl -o macham1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats02/macham1.htm
curl -o corn-14.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats02/corn-14.htm
curl -o dana-13.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats02/dana-13.htm
curl -o dana-12.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats02/dana-12.htm
curl -o nwu-11.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats02/nwu-11.htm
curl -o pac-10.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats02/pac-10.htm
curl -o sfu-9.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats02/sfu-9.htm
curl -o pac-8.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats02/pac-8.htm
curl -o sfu-7.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats02/sfu-7.htm
curl -o mlc-6.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats02/mlc-6.htm
curl -o mlc-5.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats02/mlc-5.htm
curl -o uwrf-4.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats02/uwrf-4.htm
curl -o uwrf-3.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats02/uwrf-3.htm
curl -o nwc-2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats02/nwc-2.htm
curl -o nwc-1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats02/nwc-1.htm
