curl -o 0307-1mm.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats10/0307-1mm.htm
curl -o 0307-2mm.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats10/0307-2mm.htm
curl -o 0314-bsu.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats10/0314-bsu.htm
curl -o 0314-nyu.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats10/0314-nyu.htm
curl -o 0315-osw.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats10/0315-osw.htm
curl -o 0315-rw.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats10/0315-rw.htm
curl -o 0317-fre.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats10/0317-fre.htm
curl -o 0317-whe.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats10/0317-whe.htm
curl -o 0318-ssc.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats10/0318-ssc.htm
curl -o 0318-st.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats10/0318-st.htm
curl -o 0320-np.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats10/0320-np.htm
curl -o 0320-uws.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats10/0320-uws.htm
curl -o 0327-bl1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats10/0327-bl1.htm
curl -o 0327-bl2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats10/0327-bl2.htm
curl -o 033110g1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats10/033110g1.htm
curl -o 033110g2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats10/033110g2.htm
curl -o 0408-cc1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats10/0408-cc1.htm
curl -o 0408-cc2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats10/0408-cc2.htm
curl -o 0410-sm1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats10/0410-sm1.htm
curl -o 0410-sm2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats10/0410-sm2.htm
curl -o 0417-bu1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats10/0417-bu1.htm
curl -o 0417-bu2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats10/0417-bu2.htm
curl -o 0422-sb1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats10/0422-sb1.htm
curl -o 0422-sb2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats10/0422-sb2.htm
curl -o 0424-sc1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats10/0424-sc1.htm
curl -o 0424-sc2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats10/0424-sc2.htm
curl -o 0428-ga1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats10/0428-ga1.htm
curl -o 0428-ga2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats10/0428-ga2.htm
curl -o 0501-st1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats10/0501-st1.htm
curl -o 0502-st2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats10/0502-st2.htm
curl -o 10sb30.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats10/10sb30.htm
curl -o 10sb31.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats10/10sb31.htm
curl -o hu-mac1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats10/hu-mac1.htm
curl -o hu-mac2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats10/hu-mac2.htm
curl -o hyvee1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats10/hyvee1.htm
curl -o hyvee3.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats10/hyvee3.htm
curl -o hyvee6.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats10/hyvee6.htm
curl -o hyvee9.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats10/hyvee9.htm
curl -o stomac1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats10/stomac1.htm
curl -o stomac2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats10/stomac2.htm
