curl -o 0216-ws2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats12/0216-ws2.htm
curl -o 0226-ws1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats12/0226-ws1.htm
curl -o 0306-mm1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats12/0306-mm1.htm
curl -o 0306-mm2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats12/0306-mm2.htm
curl -o 0312-frm.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats12/0312-frm.htm
curl -o 0312-frn.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats12/0312-frn.htm
curl -o 0314-mti.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats12/0314-mti.htm
curl -o 0314-rut.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats12/0314-rut.htm
curl -o 0315-hoo.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats12/0315-hoo.htm
curl -o 0315-wes.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats12/0315-wes.htm
curl -o 0316-rip.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats12/0316-rip.htm
curl -o 0316-thi.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats12/0316-thi.htm
curl -o 0324-ml1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats12/0324-ml1.htm
curl -o 0324-ml2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats12/0324-ml2.htm
curl -o 0327-bl1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats12/0327-bl1.htm
curl -o 0327-bl2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats12/0327-bl2.htm
curl -o 0328-cc1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats12/0328-cc1.htm
curl -o 0328-cc2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats12/0328-cc2.htm
curl -o 0401-sb1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats12/0401-sb1.htm
curl -o 0401-sb2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats12/0401-sb2.htm
curl -o 0405-ac1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats12/0405-ac1.htm
curl -o 0405-ac2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats12/0405-ac2.htm
curl -o 0411_ga1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats12/0411_ga1.htm
curl -o 0411_ga2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats12/0411_ga2.htm
curl -o 0417-bu1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats12/0417-bu1.htm
curl -o 0417-bu2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats12/0417-bu2.htm
curl -o 0419-sm1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats12/0419-sm1.htm
curl -o 0419-sm2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats12/0419-sm2.htm
curl -o 0425-st1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats12/0425-st1.htm
curl -o 0425-st2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats12/0425-st2.htm
curl -o 12sb34.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats12/12sb34.htm
curl -o 12sb35.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats12/12sb35.htm
curl -o mac-hu1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats12/mac-hu1.htm
curl -o mac-hu2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats12/mac-hu2.htm
curl -o mac-scu1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats12/mac-scu1.htm
curl -o macscu2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats12/macscu2.htm
curl -o sto-mac1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats12/sto-mac1.htm
curl -o sto-mac2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats12/sto-mac2.htm
