curl -o 0301-bl1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats13/0301-bl1.htm
curl -o 0301-bl2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats13/0301-bl2.htm
curl -o 0304-mm1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats13/0304-mm1.htm
curl -o 0304-mm2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats13/0304-mm2.htm
curl -o 0312-ml1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats13/0312-ml1.htm
curl -o 0312-ml2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats13/0312-ml2.htm
curl -o 0317-nec.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats13/0317-nec.htm
curl -o 0317-osu.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats13/0317-osu.htm
curl -o 0318-wne.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats13/0318-wne.htm
curl -o 0319-lu.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats13/0319-lu.htm
curl -o 0319-tuf.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats13/0319-tuf.htm
curl -o 0321-hc.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats13/0321-hc.htm
curl -o 0404-sc1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats13/0404-sc1.htm
curl -o 040713g1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats13/040713g1.htm
curl -o 040713g2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats13/040713g2.htm
curl -o 0408-1cc.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats13/0408-1cc.htm
curl -o 0408-2cc.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats13/0408-2cc.htm
curl -o 0414-hu1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats13/0414-hu1.htm
curl -o 0414-hu2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats13/0414-hu2.htm
curl -o 0427-cc1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats13/0427-cc1.htm
curl -o 0427-cc2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats13/0427-cc2.htm
curl -o 0429-so1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats13/0429-so1.htm
curl -o 0429-so2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats13/0429-so2.htm
curl -o 0430-sc2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats13/0430-sc2.htm
curl -o 130421-1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats13/130421-1.htm
curl -o 130421-2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats13/130421-2.htm
curl -o 4-25-sb1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats13/4-25-sb1.htm
curl -o 4-25-sb2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats13/4-25-sb2.htm
curl -o 427mac-2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats13/427mac-2.htm
curl -o 428mac-1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats13/428mac-1.htm
curl -o bumc-1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats13/bumc-1.htm
curl -o bumc-2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats13/bumc-2.htm
curl -o dbqmac1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats13/dbqmac1.htm
curl -o mar29a.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats13/mar29a.htm
curl -o mar29b.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats13/mar29b.htm
curl -o np-0322.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats13/np-0322.htm
curl -o sb201302.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats13/sb201302.htm
curl -o scmac3.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats13/scmac3.htm
curl -o sframac.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats13/sframac.htm
curl -o ustmac.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats13/ustmac.htm
