curl -o mac-bu2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/mac-bu2.htm
curl -o mac-bu1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/mac-bu1.htm
curl -o 0422-2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/0422-2.htm
curl -o csb3107.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/csb3107.htm
curl -o csb3007.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/csb3007.htm
curl -o 0425-sm2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/0425-sm2.htm
curl -o 0425-sm1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/0425-sm1.htm
curl -o 0423-crn.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/0423-crn.htm
curl -o 0422-1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/0422-1.htm
curl -o 0421-2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/0421-2.htm
curl -o 0421-1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/0421-1.htm
curl -o 07sb22.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/07sb22.htm
curl -o 07sb21.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/07sb21.htm
curl -o sto-mac2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/sto-mac2.htm
curl -o sto-mac.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/sto-mac.htm
curl -o mac-hu2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/mac-hu2.htm
curl -o mac-hu.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/mac-hu.htm
curl -o 4-14-07b.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/4-14-07b.htm
curl -o 4-14-07a.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/4-14-07a.htm
curl -o 0413-2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/0413-2.htm
curl -o 0413-1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/0413-1.htm
curl -o 0410-2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/0410-2.htm
curl -o 0410-1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/0410-1.htm
curl -o nwcmac3.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/nwcmac3.htm
curl -o nwcmac1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/nwcmac1.htm
curl -o 0324-2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/0324-2.htm
curl -o 0324-1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/0324-1.htm
curl -o mac-cor.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/mac-cor.htm
curl -o mac-pug.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/mac-pug.htm
curl -o mac-wes.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/mac-wes.htm
curl -o mac-cu.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/mac-cu.htm
curl -o mac-bio.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/mac-bio.htm
curl -o mac-cne.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/mac-cne.htm
curl -o hop-mac.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/hop-mac.htm
curl -o mac-las.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/mac-las.htm
curl -o mac-wpl.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/mac-wpl.htm
curl -o 0307-2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/0307-2.htm
curl -o 0307-1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats06/0307-1.htm
curl -o mac-bu2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/mac-bu2.htm
curl -o mac-bu1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/mac-bu1.htm
curl -o 0422-2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/0422-2.htm
curl -o csb3107.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/csb3107.htm
curl -o csb3007.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/csb3007.htm
curl -o 0425-sm2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/0425-sm2.htm
curl -o 0425-sm1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/0425-sm1.htm
curl -o 0423-crn.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/0423-crn.htm
curl -o 0422-1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/0422-1.htm
curl -o 0421-2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/0421-2.htm
curl -o 0421-1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/0421-1.htm
curl -o 07sb22.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/07sb22.htm
curl -o 07sb21.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/07sb21.htm
curl -o sto-mac2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/sto-mac2.htm
curl -o sto-mac.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/sto-mac.htm
curl -o mac-hu2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/mac-hu2.htm
curl -o mac-hu.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/mac-hu.htm
curl -o 4-14-07b.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/4-14-07b.htm
curl -o 4-14-07a.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/4-14-07a.htm
curl -o 0413-2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/0413-2.htm
curl -o 0413-1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/0413-1.htm
curl -o 0410-2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/0410-2.htm
curl -o 0410-1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/0410-1.htm
curl -o nwcmac3.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/nwcmac3.htm
curl -o nwcmac1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/nwcmac1.htm
curl -o 0324-2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/0324-2.htm
curl -o 0324-1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/0324-1.htm
curl -o mac-cor.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/mac-cor.htm
curl -o mac-pug.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/mac-pug.htm
curl -o mac-wes.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/mac-wes.htm
curl -o mac-cu.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/mac-cu.htm
curl -o mac-bio.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/mac-bio.htm
curl -o mac-cne.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/mac-cne.htm
curl -o hop-mac.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/hop-mac.htm
curl -o mac-las.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/mac-las.htm
curl -o mac-wpl.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/mac-wpl.htm
curl -o 0307-2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/0307-2.htm
curl -o 0307-1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/0307-1.htm
