curl -o 0312-bl1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/0312-bl1.htm
curl -o 0312-bl1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats08/0312-bl1.htm
curl -o 0312-bl2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/0312-bl2.htm
curl -o 0312-bl2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats08/0312-bl2.htm
curl -o 0316-pol.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/0316-pol.htm
curl -o 0316-pol.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats08/0316-pol.htm
curl -o 0316-tri.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/0316-tri.htm
curl -o 0316-tri.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats08/0316-tri.htm
curl -o 0317-hop.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/0317-hop.htm
curl -o 0317-hop.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats08/0317-hop.htm
curl -o 0319-end.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/0319-end.htm
curl -o 0319-end.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats08/0319-end.htm
curl -o 0319-row.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/0319-row.htm
curl -o 0319-row.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats08/0319-row.htm
curl -o 0320-car.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/0320-car.htm
curl -o 0320-car.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats08/0320-car.htm
curl -o 0320-mvn.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/0320-mvn.htm
curl -o 0320-mvn.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats08/0320-mvn.htm
curl -o 0321-mcd.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/0321-mcd.htm
curl -o 0321-mcd.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats08/0321-mcd.htm
curl -o 0321-wpu.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/0321-wpu.htm
curl -o 0321-wpu.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats08/0321-wpu.htm
curl -o 0403-1st.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/0403-1st.htm
curl -o 0403-1st.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats08/0403-1st.htm
curl -o 0403-2st.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/0403-2st.htm
curl -o 0403-2st.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats08/0403-2st.htm
curl -o 0405-1so.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/0405-1so.htm
curl -o 0405-1so.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats08/0405-1so.htm
curl -o 0405-2so.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/0405-2so.htm
curl -o 0405-2so.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats08/0405-2so.htm
curl -o 040908g1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/040908g1.htm
curl -o 040908g1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats08/040908g1.htm
curl -o 040908g2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/040908g2.htm
curl -o 040908g2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats08/040908g2.htm
curl -o 0415-sb1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/0415-sb1.htm
curl -o 0415-sb1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats08/0415-sb1.htm
curl -o 0421-bu1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/0421-bu1.htm
curl -o 0421-bu1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats08/0421-bu1.htm
curl -o 0421-bu2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/0421-bu2.htm
curl -o 0421-bu2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats08/0421-bu2.htm
curl -o 0423-sm1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/0423-sm1.htm
curl -o 0423-sm1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats08/0423-sm1.htm
curl -o 0423-sm2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/0423-sm2.htm
curl -o 0423-sm2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats08/0423-sm2.htm
curl -o 08sb27.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/08sb27.htm
curl -o 08sb27.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats08/08sb27.htm
curl -o 08sb28.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/08sb28.htm
curl -o 08sb28.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats08/08sb28.htm
curl -o 4-17sb1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/4-17sb1.htm
curl -o 4-17sb1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats08/4-17sb1.htm
curl -o 4-17sb2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/4-17sb2.htm
curl -o 4-17sb2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats08/4-17sb2.htm
curl -o 429mac1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/429mac1.htm
curl -o 429mac1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats08/429mac1.htm
curl -o 429mac2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/429mac2.htm
curl -o 429mac2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats08/429mac2.htm
curl -o csb-mac2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/csb-mac2.htm
curl -o csb-mac2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats08/csb-mac2.htm
curl -o hu-mac1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/hu-mac1.htm
curl -o hu-mac1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats08/hu-mac1.htm
curl -o hu-mac2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/hu-mac2.htm
curl -o hu-mac2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats08/hu-mac2.htm
curl -o mac1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/mac1.htm
curl -o mac1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats08/mac1.htm
curl -o mac2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/mac2.htm
curl -o mac2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats08/mac2.htm
curl -o w-mil7.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats07/w-mil7.htm
curl -o w-mil7.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats08/w-mil7.htm
