curl -o 0501-2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats05/0501-2.htm
curl -o 0501-1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats05/0501-1.htm
curl -o 0428-2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats05/0428-2.htm
curl -o 0428-1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats05/0428-1.htm
curl -o 4-26-sb2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats05/4-26-sb2.htm
curl -o 4-26-sb1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats05/4-26-sb1.htm
curl -o game27.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats05/game27.htm
curl -o game26.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats05/game26.htm
curl -o 0420-2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats05/0420-2.htm
curl -o 0420-1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats05/0420-1.htm
curl -o car-mac2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats05/car-mac2.htm
curl -o car-mac1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats05/car-mac1.htm
curl -o 0414-2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats05/0414-2.htm
curl -o 0414-1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats05/0414-1.htm
curl -o 0412-2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats05/0412-2.htm
curl -o 0412-1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats05/0412-1.htm
curl -o 0409-2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats05/0409-2.htm
curl -o 0409-1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats05/0409-1.htm
curl -o 040605g2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats05/040605g2.htm
curl -o 040605g1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats05/040605g1.htm
curl -o 0404-2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats05/0404-2.htm
curl -o 0404-1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats05/0404-1.htm
curl -o 42mac-2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats05/42mac-2.htm
curl -o 42mac-1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats05/42mac-1.htm
curl -o 0325-uwp.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats05/0325-uwp.htm
curl -o 0325-wcs.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats05/0325-wcs.htm
curl -o 0324-wes.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats05/0324-wes.htm
curl -o 0324-uws.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats05/0324-uws.htm
curl -o 0323-snc.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats05/0323-snc.htm
curl -o 0323-mil.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats05/0323-mil.htm
curl -o 0321-eh.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats05/0321-eh.htm
curl -o 0321-wj.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats05/0321-wj.htm
curl -o 0320-wj.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats05/0320-wj.htm
curl -o 0320-ram.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats05/0320-ram.htm
curl -o 2-0316.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats05/2-0316.htm
curl -o 0316-1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats05/0316-1.htm
curl -o 0309-2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats05/0309-2.htm
curl -o 0309-1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats05/0309-1.htm
