curl -o 0302-bl1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats09/0302-bl1.htm
curl -o 0302-bl2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats09/0302-bl2.htm
curl -o 0314_fsu.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats09/0314_fsu.htm
curl -o 0316-ssc.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats09/0316-ssc.htm
curl -o 0319_cu.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats09/0319_cu.htm
curl -o 0319-wsc.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats09/0319-wsc.htm
curl -o 0320-rsc.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats09/0320-rsc.htm
curl -o 0320-rwu.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats09/0320-rwu.htm
curl -o 0330-bu1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats09/0330-bu1.htm
curl -o 0330-bu2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats09/0330-bu2.htm
curl -o 0406_cc1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats09/0406_cc1.htm
curl -o 0406_cc2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats09/0406_cc2.htm
curl -o 0409-ga1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats09/0409-ga1.htm
curl -o 0409-ga2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats09/0409-ga2.htm
curl -o 0410-ac1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats09/0410-ac1.htm
curl -o 0410-ac2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats09/0410-ac2.htm
curl -o 0416-sc1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats09/0416-sc1.htm
curl -o 0416-sc2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats09/0416-sc2.htm
curl -o 0418-cc1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats09/0418-cc1.htm
curl -o 0418-cc2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats09/0418-cc2.htm
curl -o 0425-hu1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats09/0425-hu1.htm
curl -o 0425-hu2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats09/0425-hu2.htm
curl -o 0429-ml1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats09/0429-ml1.htm
curl -o 0429-ml2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats09/0429-ml2.htm
curl -o 3-17mac.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats09/3-17mac.htm
curl -o 422mac-1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats09/422mac-1.htm
curl -o 422mac-2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats09/422mac-2.htm
curl -o 4-3-sbg1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats09/4-3-sbg1.htm
curl -o 4-3-sbg2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats09/4-3-sbg2.htm
curl -o albright.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats09/albright.htm
curl -o csbmac.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats09/csbmac.htm
curl -o csbmac2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats09/csbmac2.htm
curl -o dvc-mac.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats09/dvc-mac.htm
curl -o mac-umm1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats09/mac-umm1.htm
curl -o mac-umm2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats09/mac-umm2.htm
curl -o sb31609a.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats09/sb31609a.htm
curl -o sto-mac1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats09/sto-mac1.htm
curl -o sto-mac2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats09/sto-mac2.htm
