curl -o 022714g1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats14/022714g1.htm
curl -o 022714g2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats14/022714g2.htm
curl -o 022814g5.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats14/022814g5.htm
curl -o 022814g6.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats14/022814g6.htm
curl -o 0305b-mm.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats14/0305b-mm.htm
curl -o 0305-mm1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats14/0305-mm1.htm
curl -o 03291-sb.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats14/03291-sb.htm
curl -o 03292-sb.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats14/03292-sb.htm
curl -o 0330-nc1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats14/0330-nc1.htm
curl -o 0330-nc2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats14/0330-nc2.htm
curl -o 040514g1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats14/040514g1.htm
curl -o 040514g2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats14/040514g2.htm
curl -o 0406-cc1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats14/0406-cc1.htm
curl -o 0406-cc2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats14/0406-cc2.htm
curl -o 0412-hu1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats14/0412-hu1.htm
curl -o 0412-hu2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats14/0412-hu2.htm
curl -o 0423-nw1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats14/0423-nw1.htm
curl -o 0423-nw2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats14/0423-nw2.htm
curl -o 0425scu1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats14/0425scu1.htm
curl -o 0425scu2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats14/0425scu2.htm
curl -o 0428cc1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats14/0428cc1.htm
curl -o 0428cc2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats14/0428cc2.htm
curl -o 427mac-1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats14/427mac-1.htm
curl -o 427mac-2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats14/427mac-2.htm
curl -o 4-9-sb1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats14/4-9-sb1.htm
curl -o 4-9-sb2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats14/4-9-sb2.htm
curl -o beth.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats14/beth.htm
curl -o bumc01.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats14/bumc01.htm
curl -o bumc02.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats14/bumc02.htm
curl -o elmsb01.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats14/elmsb01.htm
curl -o frsbgm09.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats14/frsbgm09.htm
curl -o gacmac~1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats14/gacmac~1.htm
curl -o gacmac~2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats14/gacmac~2.htm
curl -o macsb14.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats14/macsb14.htm
curl -o osw1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats14/osw1.htm
curl -o sto-ma~1.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats14/sto-ma~1.htm
curl -o sto-ma~2.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats14/sto-ma~2.htm
curl -o wcsb320b.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats14/wcsb320b.htm
curl -o worsb01.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats14/worsb01.htm
curl -o wpsb318a.htm https://macalester_ftp.sidearmsports.com/custompages/softball_stats/stats14/wpsb318a.htm
